server.port=4001

spring.datasource.url=jdbc:postgresql://localhost:5432/rider-db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=1780c751e9e9c17044c0678a2c1c8be9bc948d3bab76056f29b00d202f60f4a7